spring:
  application:
    name: ares-settlement
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/,http://localhost:8002/eureka/

---
spring:
  profiles: dev
server:
  port: 8030

---
spring:
  profiles: test
server:
  port: 8031

---
spring:
  profiles: prod
server:
  port: 8032