spring:
  application:
    name: ares-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  #      routes:
  #        - id: route-eureka-client
  #          uri: lb://ARES-EUREKA-CLIENT
  #          predicates:
  #            - Path=/eureka-client/**
  #        - id: route-settlement
  #          uri: lb://ARES-SETTLEMENT
  #          predicates:
  #            - Path=/settlement/**
  #        - id: route-order
  #          uri: lb://ARES-ORDER
  #          predicates:
  #            - Path=/order/**
  #            - Query=token
  #            - Method=GET
  redis:
    port: 6379
    database: 0
    host: localhost
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 5000ms

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/,http://localhost:8003/eureka/

---
spring:
  profiles: dev
server:
  port: 8020

---
spring:
  profiles: test
server:
  port: 8021

---
spring:
  profiles: prod
server:
  port: 8022