spring:
  application:
    name: ares-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ares-order
          uri: lb://ARES-ORDER
          predicates:
            - Path=/order/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1 # 令牌桶每秒填充速率
                redis-rate-limiter.burstCapacity: 2 # 令牌桶容量
                key-resolver: "#{@parameterKeyResolver}" # 使用SpEL表达式按名称引用Bean
        - id: ares-settlement
          uri: lb://ARES-SETTLEMENT
          predicates:
            - Path=/settlement/**

    redis:
      port: 6379
      database: 0
      host: localhost
      password:
      jedis:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
      timeout: 5000ms
    sentinel:
      transport:
        dashboard: localhost:8080
      filter:
        enabled: false
      eager: true

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/,http://localhost:8003/eureka/
server:
  servlet:
    context-path: /ares-gateway
---
spring:
  profiles: dev
  cloud:
    sentinel:
      transport:
        port: 8090
server:
  port: 8020

---
spring:
  profiles: test
  cloud:
    sentinel:
      transport:
        port: 8090
server:
  port: 8021

---
spring:
  profiles: prod
  cloud:
    sentinel:
      transport:
        port: 8090
server:
  port: 8022