spring:
  application:
    name: ares-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: route-eureka-client
          uri: lb://ARES-EUREKA-CLIENT
          predicates:
            - Path=/eureka-client/**
        - id: settlement
          uri: lb://ARES-SETTLEMENT
          predicates:
            - Path=/settlement/**
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/,http://localhost:8002/eureka/

---
spring:
  profiles: dev
server:
  port: 8020

---
spring:
  profiles: test
server:
  port: 8021

---
spring:
  profiles: prod
server:
  port: 8022