spring:
  application:
    name: ares-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
    url: jdbc:mysql://127.0.0.1:3306/ares_user?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/,http://localhost:8003/eureka/
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: -1
server:
  servlet:
    context-path: /user
---
spring:
  profiles: dev
server:
  port: 8030

---
spring:
  profiles: test
server:
  port: 8031

---
spring:
  profiles: prod
server:
  port: 8032