spring:
  application:
    name: ares-eureka-client
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/,http://localhost:8002/eureka/
server:
  servlet:
    context-path: /eureka-client
---
spring:
  profiles: dev
server:
  port: 8010

---
spring:
  profiles: test
server:
  port: 8011

---
spring:
  profiles: prod
server:
  port: 8012